spectaql:
  targetDir: ./docs
introspection:
  # schemaFile: ./schema.gql
  url: 'https://testnet.coopenomics.world/backend/v1/graphql'

info:
  title: 'API-Документация'
  description: 'MONO - автономная и единая точка доступа к кооперативной экономике. MONO предоставляет методы для извлечения (QUERIES), изменения (MUTATIONS) и подписок (SUBSCRIPTIONS) на информацию в локальной базе данных кооператива и распределенной базе данных кооперативной экономики, используя технологию GRAPHQL.'
  # This is non-standard and optional. If omitted, will use "title". Also, only relevant
  # when building non-embedded.
  x-htmlTitle: Your HTML page title here
  termsOfService: 'https://цифровой-кооператив.рф'
  contact:
    # name: YourSite Support
    email: support@coopenomics.world
    # url: https://yoursite.com/support
  license:
    name: BY-NC-SA 4.0
    url: 'https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.ru'

  # x-introItems:
  # Can be a Title (for the Nav panel) + URL to simply add a link to somewhere
  # - title: A silly link to our website!
  # url: http://yoursite.com
  # Can be a Title (for the Nav panel) + description (for the Content panel)
  # - title: Important thing 1
  #   description: Some important stuff we wanted you to know. Supports `markdown`
  # # Can be a Title (for the Nav panel) + file that gets loaded (for the Content panel)
  # - title: Content from file that supports markdown
  #   file: ./examples/data/intro-items-markdown.md

  # If you really want to hide the "Documentation by" at the bottom of your output, you can do so here
  # Default: false
  x-hidePoweredBy: true
  # x-url: https://testnet.coopenomics.world/backend/v1/graphql
